# Generated by Django 4.0.2 on 2022-08-24 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_calender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commentId', models.IntegerField()),
                ('feedId', models.IntegerField()),
                ('commenterImageUrl', models.CharField(max_length=256)),
                ('commenterName', models.CharField(max_length=256)),
                ('comment', models.TextField()),
                ('commentedTimestamp', models.IntegerField()),
            ],
        ),
    ]
