# Generated by Django 4.0.2 on 2022-08-24 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posterImageUrl', models.CharField(max_length=256)),
                ('posterName', models.CharField(max_length=256)),
                ('postedTimestamp', models.IntegerField()),
                ('feedType', models.CharField(max_length=256)),
                ('isSeen', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('feedPictureUrl', models.CharField(max_length=256)),
                ('feedId', models.IntegerField()),
                ('expectation', models.CharField(max_length=256)),
                ('breadcrumb', models.CharField(max_length=256)),
            ],
        ),
    ]
