# Generated by Django 4.0.2 on 2022-08-24 19:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('body', models.TextField(max_length=256)),
                ('timestamp', models.IntegerField()),
            ],
        ),
    ]
