# Generated by Django 4.0.2 on 2022-08-24 19:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=256)),
                ('parentId', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('parentImageUrl', models.CharField(max_length=256)),
                ('phoneNumber', models.CharField(max_length=256)),
                ('emailAddress', models.CharField(max_length=256)),
            ],
        ),
    ]
