# Generated by Django 4.0.2 on 2022-08-24 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parentId', models.CharField(max_length=256)),
                ('feedbackType', models.CharField(max_length=256)),
                ('feedbackDescription', models.CharField(max_length=256)),
            ],
        ),
    ]
