# Generated by Django 4.0.2 on 2022-09-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
