# Generated by Django 4.0.2 on 2022-09-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_child_childinstance_school_teacher_subject_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
