# Generated by Django 4.0.2 on 2022-09-21 19:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_remove_notification_timestamp_notification_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=256)),
                ('url', models.URLField(max_length=1000)),
                ('downloaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_instance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_instance_files', to='src.childinstance')),
            ],
        ),
    ]
